language: scala
scala:
- 2.10.6
jdk:
- oraclejdk8
before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_0d40c3508e9d_key -iv $encrypted_0d40c3508e9d_iv -in keys.tar.enc -out keys.tar -d;
    tar xvf keys.tar;
    chmod 600 deploy_key;
    cp deploy_key ~/.ssh/id_rsa;
  fi
- export PATH=${PATH}:./vendor/bundle
install:
- rvm use 2.2.3 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.2.1
script:
- sbt compile publishLocal
- sbt test scripted
- sbt kazari/fullOptGenerate
- sbt docs/tut
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    bash scripts/kazariBuild.sh;
    bash scripts/publishMicrosite.sh;
  fi
- sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess